import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./utils/lenisWrapper";

const hank = Familjen_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hank.className}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
